name: Build Shroud Services

on:
  push:
    branches: [ "main", "cdn" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ambassador, core, dispatcher, echo, persistenceworker, satellite, seekerreader, seekerwriter]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./shroud-service/Dockerfile 
          push: true
          build-args: |
            SERVICE_NAME=${{ matrix.service }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.service }}:latest
            ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ github.sha }}
